### ISSUE TITLE
Personally feel that the basic library directly panic is not very friendly, I hope it can be adjusted to error return 

### ISSUE THREAD

**Issue by conero** [forgoer/openssl#13]
> **如题**，遇到的场景如下：

比如服务器使用对应的加密方式因为客户端的错误请求直接导致服务器挂掉了，这是一个十分致命的失误！

或者增加一个前置检测函数来修复。

**Comment by techoner** [comment]
@conero Can you make a PR ?

**Comment by conero** [comment]
OK, I'll find time to get try it.
