### ISSUE TITLE
v2.0.0+incompatible.info: 404 Not Found？？？？

### ISSUE THREAD

**Issue by huizhang001** [forgoer/openssl#14]
github.com/forgoer/openssl/@v/v2.0.0+incompatible.info: 404 Not Found

**Comment by dino-ma** [comment]
+1 why?

**Comment by miniLCT** [comment]
+1 why?

**Comment by techoner** [comment]
@dino-ma @huizhang001 @miniLCT Only v1.x version .
```
require github.com/forgoer/openssl v1.1.1
```

**Comment by huizhang001** [comment]
@techoner 这俩版本完全一致吗？

**Comment by techoner** [comment]
@huizhang001 Yes, exactly the same .
