### ISSUE TITLE
mac is ok。 but linux is not right

### ISSUE THREAD

**Issue by purplecity** [forgoer/openssl#2]
* at mac is good
![image](https://user-images.githubusercontent.com/38914615/72403824-5807a080-378e-11ea-9f8e-c33a36455d9a.png)

* at ubuntu18.04 or centos 6.10 not right
![image](https://user-images.githubusercontent.com/38914615/72404144-496db900-378f-11ea-8761-c462ce899773.png)

![image](https://user-images.githubusercontent.com/38914615/72404173-5b4f5c00-378f-11ea-9404-c043d6ffce23.png)

**Comment by techoner** [comment]
@purplecity  You can try it in ubuntu with the same code as in mac.
