### ISSUE TITLE
Uncaught panic

### ISSUE THREAD

**Issue by gonejack** [forgoer/openssl#22]
Hi, author.

There is an uncaught panic popups from code

https://github.com/forgoer/openssl/blob/master/cbc.go#L35
```go
mode := cipher.NewCBCDecrypter(block, iv)
mode.CryptBlocks(dst, src)
```
making calls to openssl.Des3CBCDecrypt throws panic too.

Can you handle this panic into an error within this library, people cannot control their decoding data from internet are always valid.

**Comment by gonejack** [comment]
This is the one I runned into

https://github.com/golang/go/blob/master/src/crypto/cipher/cbc.go#L145

**Comment by leeqvip** [comment]
@gonejack So here needs to be checked in advance to return error. Man, can you submit a PR for this ?

**Comment by hopher** [comment]
https://github.com/golang/go/blob/master/src/crypto/cipher/cbc.go#L145

add panic caught in CBCDecrypt func

```
// CBCDecrypt
func CBCDecrypt(block cipher.Block, src, iv []byte, padding string) (text []byte, err error) {
	defer func() {
		if r := recover(); r != nil {
			switch t := r.(type) {
			case string:
				err = errors.New(t)
			case error:
				err = t
			default:
				err = errors.New("unknow")
			}
			err = fmt.Errorf("CBCDecrypt: %w", err)
			return
		}
	}()

	dst := make([]byte, len(src))

	if len(iv) != block.BlockSize() {
		return nil, errors.New("CBCDecrypt: IV length must equal block size")
	}

	mode := cipher.NewCBCDecrypter(block, iv)
	mode.CryptBlocks(dst, src)

	return UnPadding(padding, dst)
}
```

**Comment by leeqvip** [comment]
@hopher I think check ahead is better than recover.
