### ISSUE TITLE
Encryption/Decryption does work properly using the library but fails using OpenSSL CLI

### ISSUE THREAD

**Issue by cedricve** [forgoer/openssl#25]
Here is my class:

    package utils

    import (
        "github.com/forgoer/openssl"
    )

    type Crypter struct {
        key []byte
        iv  []byte
    }

    func NewCrypter(key []byte, iv []byte) (*Crypter, error) {
        return &Crypter{key: key, iv: iv}, nil
    }

    func (c *Crypter) Encrypt(data []byte) ([]byte, error) {
        return openssl.AesCBCEncrypt(data, c.key, c.iv, openssl.PKCS7_PADDING)
    }

    func (c *Crypter) Decrypt(data []byte) ([]byte, error) {
        return openssl.AesCBCDecrypt(data, c.key, c.iv, openssl.PKCS7_PADDING)
    }

The class is used with following `iv` and `key`.

    func EncryptFileWithSharedKey(fullname string, sharedKey string) (encryptedFile []byte, err error) {

	key := []byte("1234567890123456")
	iv := []byte("1234567890123456")

	// Initialize new crypter struct. Errors are ignored.
	crypter, _ := NewCrypter(key, iv)

	// Open the file.
	file, err := os.Open(fullname)
	if err != nil {
		log.Log.Error(err.Error())
		return
	}
	defer file.Close()

	by, _ := ioutil.ReadAll(file)
	encryptedFile, err = crypter.Encrypt(by)

	return
    }

Encryption and decryption does work properly for my files. However when encrypting using the library and decrypting through the traditional OpenSSL CLI does not work. Not sure if I'm missing something.

    % openssl enc -d -aes-256-cbc -in file_enc.mp4 -out file_dec.mp4 -a -iv 1234567890123456 -K 1234567890123456
    hex string is too short, padding with zero bytes to length
    hex string is too short, padding with zero bytes to length
    bad decrypt
    8632832704:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:crypto/evp/evp_enc.c:601:

I noticed that when encrypting through  `% openssl enc -aes-256-cbc -in ..` the `Salt__` prefix is added to the encrypted file, whereas with the library it isn't.

**Comment by leeqvip** [comment]
@cedricve The length of the key can be 16/24/32 characters (128/192/256 bits). If you use aes-256-cbc, the length of your key must be 32 characters.
