### ISSUE TITLE
AesECBDecrypt will panic if invalid src or key

### ISSUE THREAD

**Issue by tensor-flower** [forgoer/openssl#5]
AesECBDecrypt will panic if source string or key string is invalid.
You can replicate by changing function `TestAesECBDecrypt` of test file aes_test.go, in `AES-256-ECB, PKCS7_PADDING`, change any one character of either src, or key, it will cause `panic: runtime error: slice bounds out of range`.
```
func PKCS7UnPadding(src []byte) []byte {
	length := len(src)
	unpadding := int(src[length-1])
	return src[:(length - unpadding)]
}
```
Reason is unpadding is greater than length. Suggestion is to add some input validation, or check `length - unpadding` must be non-negative.

**Comment by techoner** [comment]
@tensor-flower  Can you make a PR ?

**Comment by woorui** [comment]
rebuild the travis-ci and make a realease ? @techoner
